version: "3.9"
services:
  client:
    user: root
    image: trendflowai-client:latest
    container_name: trendflowai-client
    build:
      context: ./client
      dockerfile: Dockerfile
      tags:
      - "trendflowai-client:latest"
    ports:
      - "5173:5173"
    environment:
      - SERVER_URL=http://server:5100
    #   - NODE_ENV=development
    networks:
      - trendflow

  server:
    user: root
    image: trendflowai-server:latest
    container_name: trendflowai-server
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - "trendflowai-server:latest"
    ports:
      - "5100:5100"
    # environment:
    #   - NODE_ENV=development
    networks:
      - trendflow

networks:
  trendflow:
    driver: bridge
