services:
  # client:
  #   image: trendflowai-client:latest
  #   container_name: trendflowai-client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     tags:
  #     - "trendflowai-client:latest"
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - SERVER_URL=http://server:5100
  #   networks:
  #     - trendflow

  server:
    image: trendflowai-server:latest
    container_name: trendflowai-server
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - "trendflowai-server:latest"
    environment:
      - NODE_ENV=production
    ports:
      - "5100:5100"
    networks:
      - trendflow

networks:
  trendflow:
    driver: bridge
