export const TREND_SORT_BY = {
  NEWEST: 'newest',
  OLDEST: 'oldest',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
};

export const TREND_CATEGORY = {
  PROGRAMMING_LANGUAGES: 'Programming Languages',
  FRONTEND_DEVELOPMENT: 'Frontend Development',
  BACKEND_DEVELOPMENT: 'Backend Development',
  FRONTEND_FRAMEWORK: 'Frontend Framework',
  BACKEND_FRAMEWORK: 'Backend Framework',
  DATA_SCIENCE: 'Data Science',
  QUANTUM_COMPUTING: 'Quantum Computing',
  DATABASE_TECHNOLOGIES: 'Database Technologies',
  CYBERSECURITY: 'Cybersecurity',
  SOFTWARE_AS_A_SERVICE: 'Software as a Service',
  USER_EXPERIENCE: 'User Experience',
  VIRTUAL_REALITY: 'Virtual Reality',
  QUALITY_ASSURANCE: 'Quality Assurance',
  TESTING: 'Testing',
  CLOUD_COMPUTING: 'Cloud Computing',
  API_DEVELOPMENT_TOOLS: 'API Development Tools',
  FRAMEWORKS: 'Frameworks',
  WEB_TECHNOLOGIES: 'Web Technologies',
  EDGE_COMPUTING: 'Edge Computing',
  MACHINE_LEARNING: 'Machine Learning',
  ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
  AUGMENTED_REALITY: 'Augmented Reality',
};

export const TECHNOLOGIES = {
  LANGUAGE_AGNOSTIC: 'Language Agnostic',
  BLOCKCHAIN: 'Blockchain',
  DEEP_LEARNING_AI: 'Deep Learning AI',
  NATURAL_LANGUAGE_PROCESSING: 'Natural Language Processing',
  GENERATIVE_AI: 'Generative AI',
  ADA: 'Ada',
  AEROSPIKE: 'Aerospike',
  AMAZON_AURORA: 'Amazon Aurora',
  AMAZON_DOCUMENTDB: 'Amazon DocumentDB',
  AMAZON_DYNAMODB: 'Amazon DynamoDB',
  AMAZON_REDSHIFT: 'Amazon Redshift',
  APACHE_CASSANDRA: 'Apache Cassandra',
  APACHE_DRILL: 'Apache Drill',
  APACHE_HADOOP: 'Apache Hadoop',
  APACHE_HBASE: 'Apache HBase',
  APACHE_IGNITE: 'Apache Ignite',
  APACHE_KAFKA: 'Apache Kafka',
  APACHE_SPARK: 'Apache Spark',
  ARANGODB: 'ArangoDB',
  ASCIIDOC: 'AsciiDoc',
  ASSEMBLY_LANGUAGE: 'Assembly Language',
  AWK: 'AWK',
  AZURE_COSMOS_DB: 'Azure Cosmos DB',
  BALLERINA: 'Ballerina',
  BIGTABLE: 'Bigtable',
  BLAZOR: 'Blazor',
  C: 'C',
  CASSANDRA: 'Cassandra',
  CLOJURE: 'Clojure',
  COBOL: 'Cobol',
  COCKROACHDB: 'CockroachDB',
  COUCHBASE: 'Couchbase',
  COUCHDB: 'CouchDB',
  CPP: 'C++',
  CRYSTAL: 'Crystal',
  CSS: 'CSS',
  CSHARP: 'C#',
  DART: 'Dart',
  DELPHI_OBJECT_PASCAL: 'Delphi/Object Pascal',
  DOCKER: 'Docker',
  DRUID: 'Druid',
  ELASTICSEARCH: 'Elasticsearch',
  ELIXIR: 'Elixir',
  ELM: 'Elm',
  ERLANG: 'Erlang',
  FAUNADB: 'FaunaDB',
  FIREBASE_REALTIME_DATABASE: 'Firebase Realtime Database',
  FLUTTER: 'Flutter',
  FORTRAN: 'Fortran',
  FOUNDATIONDB: 'FoundationDB',
  FSHARP: 'F#',
  GIT: 'Git',
  GO: 'Go',
  GOOGLE_CLOUD_SPANNER: 'Google Cloud Spanner',
  GRAFANA: 'Grafana',
  GRAPHDB: 'GraphDB',
  GRAPHQL: 'GraphQL',
  GREENPLUM_DATABASE: 'Greenplum Database',
  GROOVY: 'Groovy',
  HASKELL: 'Haskell',
  HTML: 'HTML',
  IBM_DB2: 'IBM Db2',
  INFLUXDB: 'InfluxDB',
  JAVA: 'Java',
  JAVASCRIPT: 'JavaScript',
  JENKINS: 'Jenkins',
  JULIA: 'Julia',
  KOTLIN: 'Kotlin',
  KUBERNETES: 'Kubernetes',
  LATEX: 'LaTeX',
  LISP: 'Lisp',
  LUA: 'Lua',
  MARKDOWN: 'Markdown',
  MARIADB: 'MariaDB',
  MATLAB: 'MATLAB',
  MEMSQL: 'MemSQL',
  MICROSOFT_AZURE_SQL_DATABASE: 'Microsoft Azure SQL Database',
  MICROSOFT_SQL_SERVER: 'Microsoft SQL Server',
  MONGODB: 'MongoDB',
  MYSQL: 'MySQL',
  NEO4J: 'Neo4j',
  NIM: 'Nim',
  NODE_JS: 'Node.js',
  OBJECTIVEC: 'Objective-C',
  OCAML: 'OCaml',
  OPENCV: 'OpenCV',
  ORACLE_DATABASE: 'Oracle Database',
  ORIENTDB: 'OrientDB',
  PANDAS: 'Pandas',
  PASCAL: 'Pascal',
  PERL: 'Perl',
  PHP: 'PHP',
  POSTGRESQL: 'PostgreSQL',
  PROLOG: 'Prolog',
  PROMETHEUS: 'Prometheus',
  PROTOBUF: 'Protocol Buffers',
  PUPPET: 'Puppet',
  PYTHON: 'Python',
  PYTORCH: 'PyTorch',
  RAVENDB: 'RavenDB',
  REASONML: 'ReasonML',
  REDIS: 'Redis',
  RETHINKDB: 'RethinkDB',
  ROCKSDB: 'RocksDB',
  RUBY: 'Ruby',
  RUST: 'Rust',
  SAP_HANA: 'SAP HANA',
  SAS: 'SAS',
  SCALA: 'Scala',
  SCHEME: 'Scheme',
  SCYLLADB: 'ScyllaDB',
  SGML: 'SGML',
  SHELL_SCRIPTING_LANGUAGES: 'Shell Scripting Languages',
  SMALLTALK: 'Smalltalk',
  SNOWFLAKE: 'Snowflake',
  SQL: 'SQL',
  SQLITE: 'SQLite',
  SWIFT: 'Swift',
  TERADATA: 'Teradata',
  TIGERGRAPH: 'TigerGraph',
  TIMESCALEDB: 'TimescaleDB',
  TYPESCRIPT: 'TypeScript',
  VBA: 'VBA',
  VOLTDB: 'VoltDB',
  XML: 'XML',
  XHTML: 'XHTML',
  YAML: 'YAML',
  YUGABYTE_DB: 'YugaByte DB',
  ZIG: 'Zig',
};
