//const BASE_URL = 'http://localhost:5100/assets';
//const CAT_URL = 'http://localhost:5100/assets/cat';
const BASE_URL = '/assets';
const CAT_URL = '/assets/cat';
const BASE_URL_VALUE = '/assets'; //first "/" is required
const CAT_URL_VALUE = '/assets/cat'; //first "/" is required

// const BASE_URL = `${
//   process.env.NODE_ENV === 'production'
//     ? process.env.PROD_URL
//     : process.env.DEV_URL
// }/assets`;
// const CAT_URL = `${
//   process.env.NODE_ENV === 'production'
//     ? process.env.PROD_URL
//     : process.env.DEV_URL
// }/assets/cat`;

//CODE BELOW DATA:
// export const trendCategoryValues = Object.values(TREND_CATEGORY).map(
//   (category) => category.value
// ); // extracting values outside of the schema & validation
// export const technologiesValues = Object.values(TECHNOLOGIES).map(
//   (tech) => tech.value
// );

/**
 * GENERATIVE_AI: {
  value: `${CAT_URL_VALUE}/generative-ai.svg`,
  label: 'Generative AI',
  image: `${CAT_URL}/generative-ai.svg`,
},
NATURAL_LANGUAGE_PROCESSING: {
  value: `${CAT_URL_VALUE}/natural-language-processing.svg`,
  label: 'Natural Language Processing (NLP)',
  image: `${CAT_URL}/natural-language-processing.svg`,
},
COMPUTER_VISION: {
  value: `${CAT_URL_VALUE}/computer-vision.svg`,
  label: 'Computer Vision',
  image: `${CAT_URL}/computer-vision.svg`,
},
MACHINE_LEARNING: {
  value: `${CAT_URL_VALUE}/machine-learning.svg`,
  label: 'Machine Learning',
  image: `${CAT_URL}/machine-learning.svg`,
},
DEEP_LEARNING: {
  value: `${CAT_URL_VALUE}/deep-learning.svg`,
  label: 'Deep Learning',
  image: `${CAT_URL}/deep-learning.svg`,
},
EDGE_AI: {
  value: `${CAT_URL_VALUE}/edge-ai.svg`,
  label: 'Edge AI',
  image: `${CAT_URL}/edge-ai.svg`,
},
AI_SECURITY: {
  value: `${CAT_URL_VALUE}/ai-security.svg`,
  label: 'AI Security',
  image: `${CAT_URL}/ai-security.svg`,
},
AI_INFRASTRUCTURE: {
  value: `${CAT_URL_VALUE}/ai-infrastructure.svg`,
  label: 'AI Infrastructure',
  image: `${CAT_URL}/ai-infrastructure.svg`,
},
ROBOTICS_AI: {
  value: `${CAT_URL_VALUE}/robotics-ai.svg`,
  label: 'Robotics AI',
  image: `${CAT_URL}/robotics-ai.svg`,
},
AUTOMATED_MACHINE_LEARNING: {
  value: `${CAT_URL_VALUE}/automl.svg`,
  label: 'Automated Machine Learning (AutoML)',
  image: `${CAT_URL}/automl.svg`,
},
 */

/**
 * USE constants_comp for comparing in changes prevent data loss
 * PLEASE NOTE: FILTER AND ADD TREND currently use the label for data passing not the VALUE filed
 */
///////////////////////////////////////////////////////////////////////////////
export const TREND_CATEGORY = {
  API_DEVELOPMENT_TOOLS: {
    fullImageUrl: `${CAT_URL_VALUE}/api-tools.svg`,
    label: 'API Development Tools',
    value: 'API Development Tools',
    image: `${CAT_URL}/api-tools.svg`,
  },
  ARTIFICIAL_INTELLIGENCE: {
    fullImageUrl: `${CAT_URL_VALUE}/ai.svg`,
    label: 'Artificial Intelligence',
    value: 'Artificial Intelligence',
    image: `${CAT_URL}/ai.svg`,
  },
  AI_MODEL_DEPLOYMENT: {
    fullImageUrl: `${CAT_URL_VALUE}/model-deployment.svg`,
    label: 'AI Model Deployment ',
    value: 'AI Model Deployment ',
    image: `${CAT_URL}/model-deployment.svg`,
  },
  AUGMENTED_REALITY: {
    fullImageUrl: `${CAT_URL_VALUE}/augmented-reality.svg`,
    label: 'Augmented Reality',
    value: 'Augmented Reality',
    image: `${CAT_URL}/augmented-reality.svg`,
  },
  BACKEND_DEVELOPMENT: {
    fullImageUrl: `${CAT_URL_VALUE}/backend-development.svg`,
    label: 'Backend Development',
    value: 'Backend Development',
    image: `${CAT_URL}/backend-development.svg`,
  },
  BACKEND_FRAMEWORK: {
    fullImageUrl: `${CAT_URL_VALUE}/backend-framework.svg`,
    label: 'Backend Framework',
    value: 'Backend Framework',
    image: `${CAT_URL}/backend-framework.svg`,
  },
  BLOCKCHAIN: {
    fullImageUrl: `${CAT_URL_VALUE}/blockchain.svg`,
    label: 'Blockchain',
    value: 'Blockchain',
    image: `${CAT_URL}/blockchain.svg`,
  },
  CASHING_SYSTEMS: {
    fullImageUrl: `${CAT_URL_VALUE}/caching.svg`,
    label: 'Caching Systems',
    value: 'Caching Systems',
    image: `${CAT_URL}/caching.svg`,
  },
  CI_CD: {
    fullImageUrl: `${CAT_URL_VALUE}/ci-cd.svg`,
    label: 'CI/CD',
    value: 'CI/CD',
    image: `${CAT_URL}/ci-cd.svg`,
  },
  CLOUD_COMPUTING: {
    fullImageUrl: `${CAT_URL_VALUE}/cloud-computing.svg`,
    label: 'Cloud Computing',
    value: 'Cloud Computing',
    image: `${CAT_URL}/cloud-computing.svg`,
  },
  CLOUD_SERVICES: {
    fullImageUrl: `${CAT_URL_VALUE}/cloud-services.svg`,
    label: 'Cloud Services',
    value: 'Cloud Services',
    image: `${CAT_URL}/cloud-services.svg`,
  },
  CONTAINERIZATION: {
    fullImageUrl: `${CAT_URL_VALUE}/containerization.svg`,
    label: 'Containerization',
    value: 'Containerization',
    image: `${CAT_URL}/containerization.svg`,
  },
  CYBERSECURITY: {
    fullImageUrl: `${CAT_URL_VALUE}/cybersecurity.svg`,
    label: 'Cybersecurity',
    value: 'Cybersecurity',
    image: `${CAT_URL}/cybersecurity.svg`,
  },
  DATA_SCIENCE: {
    fullImageUrl: `${CAT_URL_VALUE}/data-science.svg`,
    label: 'Data Science',
    value: 'Data Science',
    image: `${CAT_URL}/data-science.svg`,
  },
  DATABASE_TECHNOLOGIES: {
    fullImageUrl: `${CAT_URL_VALUE}/database-technologies.svg`,
    label: 'Database Technologies',
    value: 'Database Technologies',
    image: `${CAT_URL}/database-technologies.svg`,
  },
  DEEP_LEARNING_AI: {
    fullImageUrl: `${CAT_URL_VALUE}/deep-learning-ai.svg`,
    label: 'Deep Learning AI',
    value: 'Deep Learning AI',
    image: `${CAT_URL}/deep-learning-ai.svg`,
  },
  DEVOPS: {
    fullImageUrl: `${CAT_URL_VALUE}/devops.svg`,
    label: 'DevOps',
    value: 'DevOps',
    image: `${CAT_URL}/devops.svg`,
  },
  EDGE_COMPUTING: {
    fullImageUrl: `${CAT_URL_VALUE}/edge-computing.svg`,
    label: 'Edge Computing',
    value: 'Edge Computing',
    image: `${CAT_URL}/edge-computing.svg`,
  },
  EDGE_AI: {
    fullImageUrl: `${CAT_URL_VALUE}/edge-ai.svg`,
    label: 'Edge AI',
    value: 'Edge AI',
    image: `${CAT_URL}/edge-ai.svg`,
  },
  FRAMEWORKS: {
    fullImageUrl: `${CAT_URL_VALUE}/frameworks.svg`,
    label: 'Frameworks',
    value: 'Frameworks',
    image: `${CAT_URL}/frameworks.svg`,
  },
  FRONTEND_DEVELOPMENT: {
    fullImageUrl: `${CAT_URL_VALUE}/frontend-development.svg`,
    label: 'Frontend Development',
    value: 'Frontend Development',
    image: `${CAT_URL}/frontend-development.svg`,
  },
  FRONTEND_FRAMEWORK: {
    fullImageUrl: `${CAT_URL_VALUE}/frontend-framework.svg`,
    label: 'Frontend Framework',
    value: 'Frontend Framework',
    image: `${CAT_URL}/frontend-framework.svg`,
  },
  GENERATIVE_AI: {
    fullImageUrl: `${CAT_URL_VALUE}/generative-ai.svg`,
    label: 'Generative AI',
    value: 'Generative AI',
    image: `${CAT_URL}/generative-ai.svg`,
  },
  HYBRID_CLOUD: {
    fullImageUrl: `${CAT_URL_VALUE}/hybrid-cloud.svg`,
    label: 'Hybrid Cloud',
    value: 'Hybrid Cloud',
    image: `${CAT_URL}/hybrid-cloud.svg`,
  },
  LARGE_LANGUAGE_MODEL: {
    fullImageUrl: `${CAT_URL_VALUE}/large-language-model.svg`,
    label: 'Large Language Model',
    value: 'Large Language Model',
    image: `${CAT_URL}/large-language-model.svg`,
  },
  LOAD_BALANCING: {
    fullImageUrl: `${CAT_URL_VALUE}/load-balancing.svg`,
    label: 'Load Balancing',
    value: 'Load Balancing',
    image: `${CAT_URL}/load-balancing.svg`,
  },
  LOW_CODE_NO_CODE: {
    fullImageUrl: `${CAT_URL_VALUE}/low-code-no-code.svg`,
    label: 'Low-Code/No-Code',
    value: 'Low-Code/No-Code',
    image: `${CAT_URL}/low-code-no-code.svg`,
  },
  MACHINE_LEARNING: {
    fullImageUrl: `${CAT_URL_VALUE}/machine-learning.svg`,
    label: 'Machine Learning',
    value: 'Machine Learning',
    image: `${CAT_URL}/machine-learning.svg`,
  },
  NATURAL_LANGUAGE_PROCESSING: {
    fullImageUrl: `${CAT_URL_VALUE}/natural-language-processing.svg`,
    label: 'Natural Language Processing',
    value: 'Natural Language Processing',
    image: `${CAT_URL}/natural-language-processing.svg`,
  },
  NEWSQL: {
    fullImageUrl: `${CAT_URL_VALUE}/newsql.svg`,
    label: 'NewSQL',
    value: 'NewSQL',
    image: `${CAT_URL}/newsql.svg`,
  },
  NOSQL: {
    fullImageUrl: `${CAT_URL_VALUE}/nosql.svg`,
    label: 'NoSQL',
    value: 'NoSQL',
    image: `${CAT_URL}/nosql.svg`,
  },
  OS: {
    fullImageUrl: `${CAT_URL_VALUE}/os.svg`,
    label: 'OS',
    value: 'OS',
    image: `${CAT_URL}/os.svg`,
  },
  PROGRAMMING_LANGUAGES: {
    fullImageUrl: `${CAT_URL_VALUE}/programming-languages.svg`,
    label: 'Programming Languages',
    value: 'Programming Languages',
    image: `${CAT_URL}/programming-languages.svg`,
  },
  PAAS: {
    fullImageUrl: `${CAT_URL_VALUE}/paas.svg`,
    label: 'PaaS',
    value: 'PaaS',
    image: `${CAT_URL}/paas.svg`,
  },
  PACKAGES: {
    fullImageUrl: `${CAT_URL_VALUE}/packages.svg`,
    label: 'Packages',
    value: 'Packages',
    image: `${CAT_URL}/packages.svg`,
  },
  PACKAGE_MANAGER: {
    fullImageUrl: `${CAT_URL_VALUE}/package-manager.svg`,
    label: 'Package Manager',
    value: 'Package Manager',
    image: `${CAT_URL}/package-manager.svg`,
  },
  PROXY_SERVER: {
    fullImageUrl: `${CAT_URL_VALUE}/proxy-server.svg`,
    label: 'Proxy Server',
    value: 'Proxy Server',
    image: `${CAT_URL}/proxy-server.svg`,
  },
  QUALITY_ASSURANCE: {
    fullImageUrl: `${CAT_URL_VALUE}/quality-assurance.svg`,
    label: 'Quality Assurance',
    value: 'Quality Assurance',
    image: `${CAT_URL}/quality-assurance.svg`,
  },
  QUANTUM_COMPUTING: {
    fullImageUrl: `${CAT_URL_VALUE}/quantum-computing.svg`,
    label: 'Quantum Computing',
    value: 'Quantum Computing',
    image: `${CAT_URL}/quantum-computing.svg`,
  },
  SERVER_ARCHITECTURE: {
    fullImageUrl: `${CAT_URL_VALUE}/server-architecture.svg`,
    label: 'Server Architecture',
    value: 'Server Architecture',
    image: `${CAT_URL}/server-architecture.svg`,
  },
  SERVERLESS_ARCHITECTURE: {
    fullImageUrl: `${CAT_URL_VALUE}/serverless-architecture.svg`,
    label: 'Serverless Architecture',
    value: 'Serverless Architecture',
    image: `${CAT_URL}/serverless-architecture.svg`,
  },
  SHELL_SCRIPTING_LANGUAGES: {
    fullImageUrl: `${CAT_URL_VALUE}/shell-scripting-languages.svg`,
    label: 'Shell Scripting Languages',
    value: 'Shell Scripting Languages',
    image: `${CAT_URL}/shell-scripting-languages.svg`,
  },
  SAAS: {
    fullImageUrl: `${CAT_URL_VALUE}/saas.svg`,
    label: 'Saas',
    value: 'Saas',
    image: `${CAT_URL}/saas.svg`,
  },
  TESTING: {
    fullImageUrl: `${CAT_URL_VALUE}/testing.svg`,
    label: 'Testing',
    value: 'Testing',
    image: `${CAT_URL}/testing.svg`,
  },
  USER_EXPERIENCE: {
    fullImageUrl: `${CAT_URL_VALUE}/user-experience.svg`,
    label: 'User Experience',
    value: 'User Experience',
    image: `${CAT_URL}/user-experience.svg`,
  },
  VIRTUAL_REALITY: {
    fullImageUrl: `${CAT_URL_VALUE}/virtual-reality.svg`,
    label: 'Virtual Reality',
    value: 'Virtual Reality',
    image: `${CAT_URL}/virtual-reality.svg`,
  },
  WEB_TECHNOLOGIES: {
    fullImageUrl: `${CAT_URL_VALUE}/web-technologies.svg`,
    label: 'Web Technologies',
    value: 'Web Technologies',
    image: `${CAT_URL}/web-technologies.svg`,
  },
  WEB_SERVER: {
    fullImageUrl: `${CAT_URL_VALUE}/web-server.svg`,
    label: 'Web Server',
    value: 'Web Server',
    image: `${CAT_URL}/web-server.svg`,
  },
};
///////////////////////////////////////////////////////////////////////////////////////////////////////////
export const TECHNOLOGIES = {
  ADA: {
    fullImageUrl: `${BASE_URL_VALUE}/ada.svg`,
    label: 'Ada',
    value: 'Ada',
    image: `${BASE_URL}/ada.svg`,
  },
  AEROSPIKE: {
    fullImageUrl: `${BASE_URL_VALUE}/aerospike.svg`,
    label: 'Aerospike',
    value: 'Aerospike',
    image: `${BASE_URL}/aerospike.svg`,
  },
  AMAZON_AURORA: {
    fullImageUrl: `${BASE_URL_VALUE}/aws-rds.svg`,
    label: 'Amazon Aurora',
    value: 'Amazon Aurora',
    image: `${BASE_URL}/aws-rds.svg`,
  },
  AMAZON_DOCUMENTDB: {
    fullImageUrl: `${BASE_URL_VALUE}/aws.svg`,
    label: 'Amazon DocumentDB',
    value: 'Amazon DocumentDB',
    image: `${BASE_URL}/aws.svg`,
  },
  AMAZON_DYNAMODB: {
    fullImageUrl: `${BASE_URL_VALUE}/aws-dynamodb.svg`,
    label: 'Amazon DynamoDB',
    value: 'Amazon DynamoDB',
    image: `${BASE_URL}/aws-dynamodb.svg`,
  },
  AMAZON_REDSHIFT: {
    fullImageUrl: `${BASE_URL_VALUE}/aws.svg`,
    label: 'Amazon Redshift',
    value: 'Amazon Redshift',
    image: `${BASE_URL}/aws.svg`,
  },
  ANSIBLE: {
    fullImageUrl: `${BASE_URL_VALUE}/ansible.svg`,
    label: 'Ansible',
    value: 'Ansible',
    image: `${BASE_URL}/ansible.svg`,
  },
  APACHE: {
    fullImageUrl: `${BASE_URL_VALUE}/apache.svg`,
    label: 'Apache',
    value: 'Apache',
    image: `${BASE_URL}/apache.svg`,
  },
  APACHE_HADOOP: {
    fullImageUrl: `${BASE_URL_VALUE}/hadoop.svg`,
    label: 'Apache Hadoop',
    value: 'Apache Hadoop',
    image: `${BASE_URL}/hadoop.svg`,
  },
  APACHE_HBASE: {
    fullImageUrl: `${BASE_URL_VALUE}/hbase.svg`,
    label: 'Apache HBase',
    value: 'Apache HBase',
    image: `${BASE_URL}/hbase.svg`,
  },
  APACHE_IGNITE: {
    fullImageUrl: `${BASE_URL_VALUE}/ignite.svg`,
    label: 'Apache Ignite',
    value: 'Apache Ignite',
    image: `${BASE_URL}/ignite.svg`,
  },
  APACHE_KAFKA: {
    fullImageUrl: `${BASE_URL_VALUE}/kafka.svg`,
    label: 'Apache Kafka',
    value: 'Apache Kafka',
    image: `${BASE_URL}/kafka.svg`,
  },
  APACHE_SPARK: {
    fullImageUrl: `${BASE_URL_VALUE}/apachespark.svg`,
    label: 'Apache Spark',
    value: 'Apache Spark',
    image: `${BASE_URL}/apachespark.svg`,
  },
  API_GATEWAY: {
    fullImageUrl: `${BASE_URL_VALUE}/api-gateway.svg`,
    label: 'API Gateway',
    value: 'API Gateway',
    image: `${BASE_URL}/api-gateway.svg`,
  },
  ARANGODB: {
    fullImageUrl: `${BASE_URL_VALUE}/arangodb.svg`,
    label: 'ArangoDB',
    value: 'ArangoDB',
    image: `${BASE_URL}/arangodb.svg`,
  },
  ASCIIDOC: {
    fullImageUrl: `${BASE_URL_VALUE}/asciidoc.svg`,
    label: 'AsciiDoc',
    value: 'AsciiDoc',
    image: `${BASE_URL}/asciidoc.svg`,
  },
  ASSEMBLY_LANGUAGE: {
    fullImageUrl: `${BASE_URL_VALUE}/asm.svg`,
    label: 'Assembly Language',
    value: 'Assembly Language',
    image: `${BASE_URL}/asm.svg`,
  },
  LANGUAGE_AGNOSTIC: {
    fullImageUrl: `${BASE_URL_VALUE}/language-agnostic.svg`,
    label: 'Language Agnostic',
    value: 'Language Agnostic',
    image: `${BASE_URL}/language-agnostic.svg`,
  },
  AWK: {
    fullImageUrl: `${BASE_URL_VALUE}/awk.svg`,
    label: 'AWK',
    value: 'AWK',
    image: `${BASE_URL}/awk.svg`,
  },
  AZURE: {
    fullImageUrl: `${BASE_URL_VALUE}/azure.svg`,
    label: 'Azure',
    value: 'Azure',
    image: `${BASE_URL}/azure.svg`,
  },
  AZURE_COSMOS_DB: {
    fullImageUrl: `${BASE_URL_VALUE}/cosmosdb.svg`,
    label: 'Azure Cosmos DB',
    value: 'Azure Cosmos DB',
    image: `${BASE_URL}/cosmosdb.svg`,
  },
  AWS_LAMBDA: {
    fullImageUrl: `${BASE_URL_VALUE}/aws-lambda.svg`,
    label: 'AWS Lambda',
    value: 'AWS Lambda',
    image: `${BASE_URL}/aws-lambda.svg`,
  },
  AWS: {
    fullImageUrl: `${BASE_URL_VALUE}/aws-2.svg`,
    label: 'AWS',
    value: 'AWS',
    image: `${BASE_URL}/aws-2.svg`,
  },
  BALLERINA: {
    fullImageUrl: `${BASE_URL_VALUE}/ballerina.svg`,
    label: 'Ballerina',
    value: 'Ballerina',
    image: `${BASE_URL}/ballerina.svg`,
  },
  BIGTABLE: {
    fullImageUrl: `${BASE_URL_VALUE}/bigtable.svg`,
    label: 'Bigtable',
    value: 'Bigtable',
    image: `${BASE_URL}/bigtable.svg`,
  },
  BLAZOR: {
    fullImageUrl: `${BASE_URL_VALUE}/blazor.svg`,
    label: 'Blazor',
    value: 'Blazor',
    image: `${BASE_URL}/blazor.svg`,
  },
  C: {
    fullImageUrl: `${BASE_URL_VALUE}/c.svg`,
    label: 'C',
    value: 'C',
    image: `${BASE_URL}/c.svg`,
  },
  CADDY: {
    fullImageUrl: `${BASE_URL_VALUE}/caddy.svg`,
    label: 'Caddy',
    value: 'Caddy',
    image: `${BASE_URL}/caddy.svg`,
  },
  CASSANDRA: {
    fullImageUrl: `${BASE_URL_VALUE}/cassandra.svg`,
    label: 'Cassandra',
    value: 'Cassandra',
    image: `${BASE_URL}/cassandra.svg`,
  },
  CLOJURE: {
    fullImageUrl: `${BASE_URL_VALUE}/clojure.svg`,
    label: 'Clojure',
    value: 'Clojure',
    image: `${BASE_URL}/clojure.svg`,
  },
  COBOL: {
    fullImageUrl: `${BASE_URL_VALUE}/cobol.svg`,
    label: 'Cobol',
    value: 'Cobol',
    image: `${BASE_URL}/cobol.svg`,
  },
  COCKROACHDB: {
    fullImageUrl: `${BASE_URL_VALUE}/cockroachdb.svg`,
    label: 'CockroachDB',
    value: 'CockroachDB',
    image: `${BASE_URL}/cockroachdb.svg`,
  },
  COUCHBASE: {
    fullImageUrl: `${BASE_URL_VALUE}/couchbase.svg`,
    label: 'Couchbase',
    value: 'Couchbase',
    image: `${BASE_URL}/couchbase.svg`,
  },
  COUCHDB: {
    fullImageUrl: `${BASE_URL_VALUE}/couchdb.svg`,
    label: 'CouchDB',
    value: 'CouchDB',
    image: `${BASE_URL}/couchdb.svg`,
  },
  CLOUDFLARE: {
    fullImageUrl: `${BASE_URL_VALUE}/cloudflare.svg`,
    label: 'Cloudflare',
    value: 'Cloudflare',
    image: `${BASE_URL}/cloudflare.svg`,
  },
  CPP: {
    fullImageUrl: `${BASE_URL_VALUE}/c-plus-plus.svg`,
    label: 'C++',
    value: 'C++',
    image: `${BASE_URL}/c-plus-plus.svg`,
  },
  CRYSTAL: {
    fullImageUrl: `${BASE_URL_VALUE}/crystal.svg`,
    label: 'Crystal',
    value: 'Crystal',
    image: `${BASE_URL}/crystal.svg`,
  },
  CSS: {
    fullImageUrl: `${BASE_URL_VALUE}/css3.svg`,
    label: 'CSS',
    value: 'CSS',
    image: `${BASE_URL}/css3.svg`,
  },
  CSHARP: {
    fullImageUrl: `${BASE_URL_VALUE}/c-sharp.svg`,
    label: 'C#',
    value: 'C#',
    image: `${BASE_URL}/c-sharp.svg`,
  },
  DART: {
    fullImageUrl: `${BASE_URL_VALUE}/dart.svg`,
    label: 'Dart',
    value: 'Dart',
    image: `${BASE_URL}/dart.svg`,
  },
  DELPHI: {
    fullImageUrl: `${BASE_URL_VALUE}/delphi.svg`,
    label: 'Delphi',
    value: 'Delphi',
    image: `${BASE_URL}/delphi.svg`,
  },
  DIALOGFLOW: {
    fullImageUrl: `${BASE_URL_VALUE}/dialogflow.svg`,
    label: 'Dialogflow',
    value: 'Dialogflow',
    image: `${BASE_URL}/dialogflow.svg`,
  },
  DOCKER: {
    fullImageUrl: `${BASE_URL_VALUE}/docker.svg`,
    label: 'Docker',
    value: 'Docker',
    image: `${BASE_URL}/docker.svg`,
  },
  DRUID: {
    fullImageUrl: `${BASE_URL_VALUE}/aerospike.svg`,
    label: 'Druid',
    value: 'Druid',
    image: `${BASE_URL}/aerospike.svg`,
  },
  ELASTICSEARCH: {
    fullImageUrl: `${BASE_URL_VALUE}/elasticsearch.svg`,
    label: 'Elasticsearch',
    value: 'Elasticsearch',
    image: `${BASE_URL}/elasticsearch.svg`,
  },
  ELIXIR: {
    fullImageUrl: `${BASE_URL_VALUE}/elixir.svg`,
    label: 'Elixir',
    value: 'Elixir',
    image: `${BASE_URL}/elixir.svg`,
  },
  ELM: {
    fullImageUrl: `${BASE_URL_VALUE}/elm.svg`,
    label: 'Elm',
    value: 'Elm',
    image: `${BASE_URL}/elm.svg`,
  },
  ERLANG: {
    fullImageUrl: `${BASE_URL_VALUE}/erlang.svg`,
    label: 'Erlang',
    value: 'Erlang',
    image: `${BASE_URL}/erlang.svg`,
  },
  FAUNADB: {
    fullImageUrl: `${BASE_URL_VALUE}/fauna.svg`,
    label: 'FaunaDB',
    value: 'FaunaDB',
    image: `${BASE_URL}/fauna.svg`,
  },
  FIREBASE_REALTIME_DATABASE: {
    fullImageUrl: `${BASE_URL_VALUE}/firebase.svg`,
    label: 'Firebase Realtime Database',
    value: 'Firebase Realtime Database',
    image: `${BASE_URL}/firebase.svg`,
  },
  FLUTTER: {
    fullImageUrl: `${BASE_URL_VALUE}/flutter.svg`,
    label: 'Flutter',
    value: 'Flutter',
    image: `${BASE_URL}/flutter.svg`,
  },
  FORTRAN: {
    fullImageUrl: `${BASE_URL_VALUE}/fortran.svg`,
    label: 'Fortran',
    value: 'Fortran',
    image: `${BASE_URL}/fortran.svg`,
  },
  FOUNDATIONDB: {
    fullImageUrl: `${BASE_URL_VALUE}/foundationdb.svg`,
    label: 'FoundationDB',
    value: 'FoundationDB',
    image: `${BASE_URL}/foundationdb.svg`,
  },
  FSHARP: {
    fullImageUrl: `${BASE_URL_VALUE}/fsharp.svg`,
    label: 'F#',
    value: 'F#',
    image: `${BASE_URL}/fsharp.svg`,
  },
  GIT: {
    fullImageUrl: `${BASE_URL_VALUE}/git.svg`,
    label: 'Git',
    value: 'Git',
    image: `${BASE_URL}/git.svg`,
  },
  GITHUB: {
    fullImageUrl: `${BASE_URL_VALUE}/github-actions.svg`,
    label: 'GitHub',
    value: 'GitHub',
    image: `${BASE_URL}/github-actions.svg`,
  },
  GITLAB: {
    fullImageUrl: `${BASE_URL_VALUE}/gitlab.svg`,
    label: 'GitLab',
    value: 'GitLab',
    image: `${BASE_URL}/gitlab.svg`,
  },
  GO: {
    fullImageUrl: `${BASE_URL_VALUE}/go.svg`,
    label: 'Go',
    value: 'Go',
    image: `${BASE_URL}/go.svg`,
  },
  GCP_BIGQUERY: {
    fullImageUrl: `${BASE_URL_VALUE}/bigquery.svg`,
    label: 'Google Cloud BigQuery',
    value: 'Google Cloud BigQuery',
    image: `${BASE_URL}/bigquery.svg`,
  },
  GOOGLE_CLOUD_SPANNER: {
    fullImageUrl: `${BASE_URL_VALUE}/spanner.svg`,
    label: 'Google Cloud Spanner',
    value: 'Google Cloud Spanner',
    image: `${BASE_URL}/spanner.svg`,
  },
  GOOGLE_CLOUD_FUNCTIONS: {
    fullImageUrl: `${BASE_URL_VALUE}/google-cloud-functions.svg`,
    label: 'Google Cloud Functions',
    value: 'Google Cloud Functions',
    image: `${BASE_URL}/google-cloud-functions.svg`,
  },
  GRAFANA: {
    fullImageUrl: `${BASE_URL_VALUE}/grafana.svg`,
    label: 'Grafana',
    value: 'Grafana',
    image: `${BASE_URL}/grafana.svg`,
  },
  GRAPHDB: {
    fullImageUrl: `${BASE_URL_VALUE}/aerospike.svg`,
    label: 'GraphDB',
    value: 'GraphDB',
    image: `${BASE_URL}/aerospike.svg`,
  },
  GRAPHQL: {
    fullImageUrl: `${BASE_URL_VALUE}/graphql.svg`,
    label: 'GraphQL',
    value: 'GraphQL',
    image: `${BASE_URL}/graphql.svg`,
  },
  GROOVY: {
    fullImageUrl: `${BASE_URL_VALUE}/groovy.svg`,
    label: 'Groovy',
    value: 'Groovy',
    image: `${BASE_URL}/groovy.svg`,
  },
  HUGGING_FACE: {
    fullImageUrl: `${BASE_URL_VALUE}/hugging.svg`,
    label: 'Hugging Face',
    value: 'Hugging Face',
    image: `${BASE_URL}/hugging.svg`,
  },
  HASKELL: {
    fullImageUrl: `${BASE_URL_VALUE}/haskell.svg`,
    label: 'Haskell',
    value: 'Haskell',
    image: `${BASE_URL}/haskell.svg`,
  },
  HAPROXY: {
    fullImageUrl: `${BASE_URL_VALUE}/haproxy.svg`,
    label: 'HAProxy',
    value: 'HAProxy',
    image: `${BASE_URL}/haproxy.svg`,
  },
  HTML: {
    fullImageUrl: `${BASE_URL_VALUE}/html5.svg`,
    label: 'HTML',
    value: 'HTML',
    image: `${BASE_URL}/html5.svg`,
  },
  IBM: {
    fullImageUrl: `${BASE_URL_VALUE}/ibm.svg`,
    label: 'IBM',
    value: 'IBM',
    image: `${BASE_URL}/ibm.svg`,
  },
  IBM_DB2: {
    fullImageUrl: `${BASE_URL_VALUE}/ibm-db2.svg`,
    label: 'IBM Db2',
    value: 'IBM Db2',
    image: `${BASE_URL}/ibm-db2.svg`,
  },
  INFLUXDB: {
    fullImageUrl: `${BASE_URL_VALUE}/influxdb.svg`,
    label: 'InfluxDB',
    value: 'InfluxDB',
    image: `${BASE_URL}/influxdb.svg`,
  },
  JAVA: {
    fullImageUrl: `${BASE_URL_VALUE}/java.svg`,
    label: 'Java',
    value: 'Java',
    image: `${BASE_URL}/java.svg`,
  },
  JAVASCRIPT: {
    fullImageUrl: `${BASE_URL_VALUE}/javascript.svg`,
    label: 'JavaScript',
    value: 'JavaScript',
    image: `${BASE_URL}/javascript.svg`,
  },
  JENKINS: {
    fullImageUrl: `${BASE_URL_VALUE}/jenkins.svg`,
    label: 'Jenkins',
    value: 'Jenkins',
    image: `${BASE_URL}/jenkins.svg`,
  },
  JULIA: {
    fullImageUrl: `${BASE_URL_VALUE}/julia.svg`,
    label: 'Julia',
    value: 'Julia',
    image: `${BASE_URL}/julia.svg`,
  },
  JSON: {
    fullImageUrl: `${BASE_URL_VALUE}/json.svg`,
    label: 'JSON',
    value: 'JSON',
    image: `${BASE_URL}/json.svg`,
  },
  KOTLIN: {
    fullImageUrl: `${BASE_URL_VALUE}/kotlin.svg`,
    label: 'Kotlin',
    value: 'Kotlin',
    image: `${BASE_URL}/kotlin.svg`,
  },
  KUBERNETES: {
    fullImageUrl: `${BASE_URL_VALUE}/kubernetes.svg`,
    label: 'Kubernetes',
    value: 'Kubernetes',
    image: `${BASE_URL}/kubernetes.svg`,
  },
  LATEX: {
    fullImageUrl: `${BASE_URL_VALUE}/latex.svg`,
    label: 'LaTeX',
    value: 'LaTeX',
    image: `${BASE_URL}/latex.svg`,
  },
  LISP: {
    fullImageUrl: `${BASE_URL_VALUE}/lisp.svg`,
    label: 'Lisp',
    value: 'Lisp',
    image: `${BASE_URL}/lisp.svg`,
  },
  LIGHTTPD: {
    fullImageUrl: `${BASE_URL_VALUE}/lighttpd.svg`,
    label: 'Lighttpd',
    value: 'Lighttpd',
    image: `${BASE_URL}/lighttpd.svg`,
  },
  LUA: {
    fullImageUrl: `${BASE_URL_VALUE}/lua.svg`,
    label: 'Lua',
    value: 'Lua',
    image: `${BASE_URL}/lua.svg`,
  },
  MARKDOWN: {
    fullImageUrl: `${BASE_URL_VALUE}/markdown.svg`,
    label: 'Markdown',
    value: 'Markdown',
    image: `${BASE_URL}/markdown.svg`,
  },
  MARIADB: {
    fullImageUrl: `${BASE_URL_VALUE}/mariadb.svg`,
    label: 'MariaDB',
    value: 'MariaDB',
    image: `${BASE_URL}/mariadb.svg`,
  },
  MATLAB: {
    fullImageUrl: `${BASE_URL_VALUE}/matlab.svg`,
    label: 'MATLAB',
    value: 'MATLAB',
    image: `${BASE_URL}/matlab.svg`,
  },
  MEMCACHED: {
    fullImageUrl: `${BASE_URL_VALUE}/memcached.svg`,
    label: 'Memcached',
    value: 'Memcached',
    image: `${BASE_URL}/memcached.svg`,
  },
  MEMSQL: {
    fullImageUrl: `${BASE_URL_VALUE}/memsql.svg`,
    label: 'MemSQL',
    value: 'MemSQL',
    image: `${BASE_URL}/memsql.svg`,
  },
  MICROSOFT_AZURE_SQL_DATABASE: {
    fullImageUrl: `${BASE_URL_VALUE}/sql-azure-db.svg`,
    label: 'Microsoft Azure SQL Database',
    value: 'Microsoft Azure SQL Database',
    image: `${BASE_URL}/sql-azure-db.svg`,
  },
  MICROSOFT_SQL_SERVER: {
    fullImageUrl: `${BASE_URL_VALUE}/microsoft.svg`,
    label: 'Microsoft SQL Server',
    value: 'Microsoft SQL Server',
    image: `${BASE_URL}/microsoft.svg`,
  },
  MONGODB: {
    fullImageUrl: `${BASE_URL_VALUE}/mongodb.svg`,
    label: 'MongoDB',
    value: 'MongoDB',
    image: `${BASE_URL}/mongodb.svg`,
  },
  MOJO: {
    fullImageUrl: `${BASE_URL_VALUE}/mojo.svg`,
    label: 'Mojo',
    value: 'Mojo',
    image: `${BASE_URL}/mojo.svg`,
  },
  MYSQL: {
    fullImageUrl: `${BASE_URL_VALUE}/mysql.svg`,
    label: 'MySQL',
    value: 'MySQL',
    image: `${BASE_URL}/mysql.svg`,
  },
  NEO4J: {
    fullImageUrl: `${BASE_URL_VALUE}/neo4j.svg`,
    label: 'Neo4j',
    value: 'Neo4j',
    image: `${BASE_URL}/neo4j.svg`,
  },
  NIM: {
    fullImageUrl: `${BASE_URL_VALUE}/nim.svg`,
    label: 'Nim',
    value: 'Nim',
    image: `${BASE_URL}/nim.svg`,
  },
  NODE_JS: {
    fullImageUrl: `${BASE_URL_VALUE}/nodejs.svg`,
    label: 'Node.js',
    value: 'Node.js',
    image: `${BASE_URL}/nodejs.svg`,
  },
  NGINX: {
    fullImageUrl: `${BASE_URL_VALUE}/nginx.svg`,
    label: 'Nginx',
    value: 'Nginx',
    image: `${BASE_URL}/nginx.svg`,
  },
  OBJECTIVEC: {
    fullImageUrl: `${BASE_URL_VALUE}/objectivec.svg`,
    label: 'Objective-C',
    value: 'Objective-C',
    image: `${BASE_URL}/objectivec.svg`,
  },
  OCAML: {
    fullImageUrl: `${BASE_URL_VALUE}/ocaml.svg`,
    label: 'OCaml',
    value: 'OCaml',
    image: `${BASE_URL}/ocaml.svg`,
  },
  OPENCV: {
    fullImageUrl: `${BASE_URL_VALUE}/opencv.svg`,
    label: 'OpenCV',
    value: 'OpenCV',
    image: `${BASE_URL}/opencv.svg`,
  },
  ORACLE_DATABASE: {
    fullImageUrl: `${BASE_URL_VALUE}/oracle.svg`,
    label: 'Oracle Database',
    value: 'Oracle Database',
    image: `${BASE_URL}/oracle.svg`,
  },
  ORIENTDB: {
    fullImageUrl: `${BASE_URL_VALUE}/database.svg`,
    label: 'OrientDB',
    value: 'OrientDB',
    image: `${BASE_URL}/database.svg`,
  },
  OPENAI: {
    fullImageUrl: `${BASE_URL_VALUE}/openai.svg`,
    label: 'OpenAI',
    value: 'OpenAI',
    image: `${BASE_URL}/openai.svg`,
  },
  PANDAS: {
    fullImageUrl: `${BASE_URL_VALUE}/pandas.svg`,
    label: 'Pandas',
    value: 'Pandas',
    image: `${BASE_URL}/pandas.svg`,
  },
  OBJECT_PASCAL: {
    fullImageUrl: `${BASE_URL_VALUE}/pascal.svg`,
    label: 'Object Pascal',
    value: 'Object Pascal',
    image: `${BASE_URL}/pascal.svg`,
  },
  PERL: {
    fullImageUrl: `${BASE_URL_VALUE}/perl.svg`,
    label: 'Perl',
    value: 'Perl',
    image: `${BASE_URL}/perl.svg`,
  },
  PHP: {
    fullImageUrl: `${BASE_URL_VALUE}/php.svg`,
    label: 'PHP',
    value: 'PHP',
    image: `${BASE_URL}/php.svg`,
  },
  POSTGRESQL: {
    fullImageUrl: `${BASE_URL_VALUE}/postgresql.svg`,
    label: 'PostgreSQL',
    value: 'PostgreSQL',
    image: `${BASE_URL}/postgresql.svg`,
  },
  PROLOG: {
    fullImageUrl: `${BASE_URL_VALUE}/prolog.svg`,
    label: 'Prolog',
    value: 'Prolog',
    image: `${BASE_URL}/prolog.svg`,
  },
  PROMETHEUS: {
    fullImageUrl: `${BASE_URL_VALUE}/prometheus.svg`,
    label: 'Prometheus',
    value: 'Prometheus',
    image: `${BASE_URL}/prometheus.svg`,
  },
  PROTOBUF: {
    fullImageUrl: `${BASE_URL_VALUE}/protobuf.svg`,
    label: 'Protocol Buffers',
    value: 'Protocol Buffers',
    image: `${BASE_URL}/protobuf.svg`,
  },
  PUPPET: {
    fullImageUrl: `${BASE_URL_VALUE}/puppet.svg`,
    label: 'Puppet',
    value: 'Puppet',
    image: `${BASE_URL}/puppet.svg`,
  },
  PYTHON: {
    fullImageUrl: `${BASE_URL_VALUE}/python.svg`,
    label: 'Python',
    value: 'Python',
    image: `${BASE_URL}/python.svg`,
  },
  PYTORCH: {
    fullImageUrl: `${BASE_URL_VALUE}/pytorch.svg`,
    label: 'PyTorch',
    value: 'PyTorch',
    image: `${BASE_URL}/pytorch.svg`,
  },
  RAVENDB: {
    fullImageUrl: `${BASE_URL_VALUE}/ravendb.svg`,
    label: 'RavenDB',
    value: 'RavenDB',
    image: `${BASE_URL}/ravendb.svg`,
  },
  REASONML: {
    fullImageUrl: `${BASE_URL_VALUE}/reasonml.svg`,
    label: 'ReasonML',
    value: 'ReasonML',
    image: `${BASE_URL}/reasonml.svg`,
  },
  REDIS: {
    fullImageUrl: `${BASE_URL_VALUE}/redis.svg`,
    label: 'Redis',
    value: 'Redis',
    image: `${BASE_URL}/redis.svg`,
  },
  RETHINKDB: {
    fullImageUrl: `${BASE_URL_VALUE}/rethinkdb.svg`,
    label: 'RethinkDB',
    value: 'RethinkDB',
    image: `${BASE_URL}/rethinkdb.svg`,
  },
  ROCKSDB: {
    fullImageUrl: `${BASE_URL_VALUE}/rocksdb.svg`,
    label: 'RocksDB',
    value: 'RocksDB',
    image: `${BASE_URL}/rocksdb.svg`,
  },
  RUBY: {
    fullImageUrl: `${BASE_URL_VALUE}/ruby.svg`,
    label: 'Ruby',
    value: 'Ruby',
    image: `${BASE_URL}/ruby.svg`,
  },
  RUST: {
    fullImageUrl: `${BASE_URL_VALUE}/rust.svg`,
    label: 'Rust',
    value: 'Rust',
    image: `${BASE_URL}/rust.svg`,
  },
  SAP_HANA: {
    fullImageUrl: `${BASE_URL_VALUE}/sap.svg`,
    label: 'SAP HANA',
    value: 'SAP HANA',
    image: `${BASE_URL}/sap.svg`,
  },
  SAS: {
    fullImageUrl: `${BASE_URL_VALUE}/sas.svg`,
    label: 'SAS',
    value: 'SAS',
    image: `${BASE_URL}/sas.svg`,
  },
  SALESFORCE: {
    fullImageUrl: `${BASE_URL_VALUE}/salesforce.svg`,
    label: 'Salesforce',
    value: 'Salesforce',
    image: `${BASE_URL}/salesforce.svg`,
  },
  SCALA: {
    fullImageUrl: `${BASE_URL_VALUE}/scala.svg`,
    label: 'Scala',
    value: 'Scala',
    image: `${BASE_URL}/scala.svg`,
  },
  SCHEME: {
    fullImageUrl: `${BASE_URL_VALUE}/scheme.svg`,
    label: 'Scheme',
    value: 'Scheme',
    image: `${BASE_URL}/scheme.svg`,
  },
  SCYLLADB: {
    fullImageUrl: `${BASE_URL_VALUE}/scylladb.svg`,
    label: 'ScyllaDB',
    value: 'ScyllaDB',
    image: `${BASE_URL}/scylladb.svg`,
  },
  SGML: {
    fullImageUrl: `${BASE_URL_VALUE}/programing-language.svg`,
    label: 'SGML',
    value: 'SGML',
    image: `${BASE_URL}/programing-language.svg`,
  },
  SHOPIFY: {
    fullImageUrl: `${BASE_URL_VALUE}/shopify.svg`,
    label: 'Shopify',
    value: 'Shopify',
    image: `${BASE_URL}/shopify.svg`,
  },
  SMALLTALK: {
    fullImageUrl: `${BASE_URL_VALUE}/programing-language.svg`,
    label: 'Smalltalk',
    value: 'Smalltalk',
    image: `${BASE_URL}/programing-language.svg`,
  },
  SNOWFLAKE: {
    fullImageUrl: `${BASE_URL_VALUE}/snowflake.svg`,
    label: 'Snowflake',
    value: 'Snowflake',
    image: `${BASE_URL}/snowflake.svg`,
  },
  SQL: {
    fullImageUrl: `${BASE_URL_VALUE}/sql.svg`,
    label: 'SQL',
    value: 'SQL',
    image: `${BASE_URL}/sql.svg`,
  },
  SQLITE: {
    fullImageUrl: `${BASE_URL_VALUE}/sqlite.svg`,
    label: 'SQLite',
    value: 'SQLite',
    image: `${BASE_URL}/sqlite.svg`,
  },
  SWIFT: {
    fullImageUrl: `${BASE_URL_VALUE}/swift.svg`,
    label: 'Swift',
    value: 'Swift',
    image: `${BASE_URL}/swift.svg`,
  },
  TERADATA: {
    fullImageUrl: `${BASE_URL_VALUE}/teradata.svg`,
    label: 'Teradata',
    value: 'Teradata',
    image: `${BASE_URL}/teradata.svg`,
  },
  TENSORFLOW_EXTENDED: {
    fullImageUrl: `${BASE_URL_VALUE}/tensorflow.svg`,
    label: 'TensorFlow Extended (TFX)',
    value: 'TensorFlow Extended (TFX)',
    image: `${BASE_URL}/tensorflow.svg`,
  },
  TIGERGRAPH: {
    fullImageUrl: `${BASE_URL_VALUE}/tigergraph.svg`,
    label: 'TigerGraph',
    value: 'TigerGraph',
    image: `${BASE_URL}/tigergraph.svg`,
  },
  TIMESCALEDB: {
    fullImageUrl: `${BASE_URL_VALUE}/timescaledb.svg`,
    label: 'TimescaleDB',
    value: 'TimescaleDB',
    image: `${BASE_URL}/timescaledb.svg`,
  },
  TOMCAT: {
    fullImageUrl: `${BASE_URL_VALUE}/tomcat.svg`,
    label: 'Tomcat',
    value: 'Tomcat',
    image: `${BASE_URL}/tomcat.svg`,
  },
  TRAEFIK: {
    fullImageUrl: `${BASE_URL_VALUE}/traefik.svg`,
    label: 'Traefik',
    value: 'Traefik',
    image: `${BASE_URL}/traefik.svg`,
  },
  TYPESCRIPT: {
    fullImageUrl: `${BASE_URL_VALUE}/typescript.svg`,
    label: 'TypeScript',
    value: 'TypeScript',
    image: `${BASE_URL}/typescript.svg`,
  },
  VBA: {
    fullImageUrl: `${BASE_URL_VALUE}/vba.svg`,
    label: 'VBA',
    value: 'VBA',
    image: `${BASE_URL}/vba.svg`,
  },
  VOLTDB: {
    fullImageUrl: `${BASE_URL_VALUE}/voltdb.svg`,
    label: 'VoltDB',
    value: 'VoltDB',
    image: `${BASE_URL}/voltdb.svg`,
  },
  WEBASSEMBLY: {
    fullImageUrl: `${BASE_URL_VALUE}/webassembly.svg`,
    label: 'WebAssembly',
    value: 'WebAssembly',
    image: `${BASE_URL}/webassembly.svg`,
  },
  WORDPRESS: {
    fullImageUrl: `${BASE_URL_VALUE}/wordpress.svg`,
    label: 'WordPress',
    value: 'WordPress',
    image: `${BASE_URL}/wordpress.svg`,
  },
  XHTML: {
    fullImageUrl: `${BASE_URL_VALUE}/xhtml.svg`,
    label: 'XHTML',
    value: 'XHTML',
    image: `${BASE_URL}/xhtml.svg`,
  },
  XML: {
    fullImageUrl: `${BASE_URL_VALUE}/xml.svg`,
    label: 'XML',
    value: 'XML',
    image: `${BASE_URL}/xml.svg`,
  },
  YAML: {
    fullImageUrl: `${BASE_URL_VALUE}/yaml.svg`,
    label: 'YAML',
    value: 'YAML',
    image: `${BASE_URL}/yaml.svg`,
  },
  YUGABYTE_DB: {
    fullImageUrl: `${BASE_URL_VALUE}/yugabyte.svg`,
    label: 'YugaByte DB',
    value: 'YugaByte DB',
    image: `${BASE_URL}/yugabyte.svg`,
  },
  ZIG: {
    fullImageUrl: `${BASE_URL_VALUE}/zig.svg`,
    label: 'Zig',
    value: 'Zig',
    image: `${BASE_URL}/zig.svg`,
  },
};
///////////////////////////////////////////////////////////////////////////////
export const trendCategoryValues = Object.values(TREND_CATEGORY).map(
  (category) => category.label // Compare labels, not URLs
);

export const technologiesValues = Object.values(TECHNOLOGIES).map(
  (tech) => tech.label // Compare labels, not URLs
); //extracting values outside of the schema & validation
