export const TREND_SORT_BY = {
  NEWEST: 'newest',
  OLDEST: 'oldest',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
};

export const TREND_CATEGORY = {
  PROGRAMMING_LANGUAGES: 'Programming Languages',
  FRONTEND_DEVELOPMENT: 'Frontend Development',
  BACKEND_DEVELOPMENT: 'Backend Development',
  FRONTEND_FRAMEWORK: 'Frontend Framework',
  BACKEND_FRAMEWORK: 'Backend Framework',
  DATA_SCIENCE: 'Data Science',
  DATABASE_TECHNOLOGIES: 'Database Technologies',
  CYBERSECURITY: 'Cybersecurity',
  SOFTWARE_AS_A_SERVICE: 'Software as a Service',
  USER_EXPERIENCE: 'User Experience',
  VIRTUAL_REALITY: 'Virtual Reality',
  QUALITY_ASSURANCE: 'Quality Assurance',
  TESTING: 'Testing',
  CLOUD_COMPUTING: 'Cloud Computing',
  API_DEVELOPMENT_TOOLS: 'API Development Tools',
  FRAMEWORKS: 'Frameworks',
  WEB_TECHNOLOGIES: 'Web Technologies',
  EDGE_COMPUTING: 'Edge Computing',
  NATURAL_LANGUAGE: 'Natural Language',
  MACHINE_LEARNING: 'Machine Learning',
};

export const TECHNOLOGIES = {
  PYTHON: 'Python',
  JAVASCRIPT: 'JavaScript',
  JAVA: 'Java',
  CSHARP: 'C#',
  CPP: 'C++',
  C: 'C',
  RUBY: 'Ruby',
  PHP: 'PHP',
  SWIFT: 'Swift',
  KOTLIN: 'Kotlin',
  GO: 'Go',
  TYPESCRIPT: 'TypeScript',
  SCALA: 'Scala',
  RUST: 'Rust',
  R: 'R',
  OBJECTIVEC: 'Objective-C',
  PERL: 'Perl',
  DART: 'Dart',
  LUA: 'Lua',
  GROOVY: 'Groovy',
  ELIXIR: 'Elixir',
  FSHARP: 'F#',
  HASKELL: 'Haskell',
  CLOJURE: 'Clojure',
  ERLANG: 'Erlang',
  JULIA: 'Julia',
  SHELL_SCRIPTING_LANGUAGES: 'Shell Scripting Languages',
  MATLAB: 'MATLAB',
  FORTRAN: 'Fortran',
  ADA: 'Ada',
  PASCAL: 'Pascal',
  PROLOG: 'Prolog',
  LISP: 'Lisp',
  SCHEME: 'Scheme',
  ASSEMBLY_LANGUAGE: 'Assembly Language',
  VBA: 'VBA',
  SQL: 'SQL',
  SAS: 'SAS',
  AWK: 'AWK',
  SMALLTALK: 'Smalltalk',
  DELPHI_OBJECT_PASCAL: 'Delphi/Object Pascal',
  OCAML: 'OCaml',
  CRYSTAL: 'Crystal',
  ZIG: 'Zig',
  NIM: 'Nim',
  BALLARINA: 'Ballarina',
  ELM: 'Elm',
  REASONML: 'ReasonML',
  HTML: 'HTML',
  CSS: 'CSS',
  XML: 'XML',
  XHTML: 'XHTML',
  MARKDOWN: 'Markdown',
  YAML: 'YAML',
  LATEX: 'LaTeX',
  ASCIIDOC: 'AsciiDoc',
  SGML: 'SGML',
  MYSQL: 'MySQL',
  POSTGRESQL: 'PostgreSQL',
  MICROSOFT_SQL_SERVER: 'Microsoft SQL Server',
  ORACLE_DATABASE: 'Oracle Database',
  MONGODB: 'MongoDB',
  SQLITE: 'SQLite',
  MARIADB: 'MariaDB',
  IBM_DB2: 'IBM Db2',
  REDIS: 'Redis',
  CASSANDRA: 'Cassandra',
  NEO4J: 'Neo4j',
  ELASTICSEARCH: 'Elasticsearch',
  COUCHBASE: 'Couchbase',
  FIREBASE_REALTIME_DATABASE: 'Firebase Realtime Database',
  AMAZON_DYNAMODB: 'Amazon DynamoDB',
  COCKROACHDB: 'CockroachDB',
  APACHE_HBASE: 'Apache HBase',
  ARANGODB: 'ArangoDB',
  GOOGLE_CLOUD_SPANNER: 'Google Cloud Spanner',
  AEROSPIKE: 'Aerospike',
  SAP_HANA: 'SAP HANA',
  INFLUXDB: 'InfluxDB',
  RAVENDB: 'RavenDB',
  AMAZON_AURORA: 'Amazon Aurora',
  MICROSOFT_AZURE_SQL_DATABASE: 'Microsoft Azure SQL Database',
  SNOWFLAKE: 'Snowflake',
  COSMOS_DB: 'Cosmos DB',
  ORIENTDB: 'OrientDB',
  RETHINKDB: 'RethinkDB',
  SCYLLADB: 'ScyllaDB',
  FAUNADB: 'FaunaDB',
  FOUNDATIONDB: 'FoundationDB',
  GRAPHDB: 'GraphDB',
  YUGABYTE_DB: 'YugaByte DB',
  TIMESCALEDB: 'TimescaleDB',
  AMAZON_REDSHIFT: 'Amazon Redshift',
  TERADATA: 'Teradata',
  COUCHDB: 'CouchDB',
  BIGTABLE: 'Bigtable',
  CLICKHOUSE: 'ClickHouse',
  VOLTDB: 'VoltDB',
  GREENPLUM_DATABASE: 'Greenplum Database',
  MEMSQL: 'MemSQL',
  AMAZON_DOCUMENTDB: 'Amazon DocumentDB',
  TIGERGRAPH: 'TigerGraph',
  ROCKSDB: 'RocksDB',
  DRUID: 'Druid',
  APACHE_IGNITE: 'Apache Ignite',
};
