export const MAX_TOKENS_POST = 1700; // 'Main article body'
export const MAX_TOKENS_DESC = 200; // 'Summary'
export const MAX_TOKENS_USE = 400; //"Use Cases"

//Rules for the GPT4 to follow when writing the tutorial it self:
export const SYSTEM_ROLE_POST =
  'You are an expert Technology Software Engineer Technical Tutorials writer, focusing on technology trends. Use technical terms and expert language, but ensure the content is still easy to read and understand. Adhere to the latest best practices in technical writing.';

//Asking GPT4 to generate the tutorial in a specific way. Will need to be raised once tokens are higher:
export const USER_ROLE_POST = `Generate a step-by-step technical tutorial on the topics I will provide you. The content must be formatted in SEO-friendly HTML using only these HTML tags: p, h2, h3, h4, h5, h6, strong, li, ol, ul, i, code, pre. Do not use markdown formatting or the h1 tag. Always include as much code as possible by showing relevant code snippets in code blocks using the following format: <pre><code class="language-<add_name>">. Include practical advice, detailed examples, and explain how the technology can benefit startups or developers. The guide should be informative, detailed, and easy to follow. Aim for a complete and thorough guide that naturally utilizes up to ${MAX_TOKENS_POST} tokens detailed and well-structured explanation, but do not strictly limit the output by a fixed character count.`;

//Asking GPT4 to add a website link to the trend it wrote about
export const TREND_URL_BUTTON =
  'Finally, using your latest dataset, add the official website link to the trend you wrote about at the bottom of the blog. Use the provided HTML format: <a href="trend_official_site" class="btn">Official Website</a>. If you are unable to find the official website based on your current training dataset, return nothing.';

//Rules for GPT3.5 to be a good summarizer:
export const DESC_SYSTEM_ROLE =
  'You are an intelligent technology summarizer. Your task is to take this Technical Tutorial and output concise, informative descriptions that quickly convey what the technology is used for.';

//Asking GPT3.5 to take the tutorial generated by GPT4 and summarize it
export const RESPONSE_USER_DESC =
  'I will provide you with a Technical Tutorial guide. Based on it, provide a very short and straightforward description of the technology, maximum 100 characters. Do not include the technology name in the description; only provide a straightforward explanation.';

//
//Rules for GPT3.5 for how to describe best case use for the technology in the tutorial
export const USE_SYSTEM_ROLE =
  'I will provide you with a Technical Tutorial guide do not include it in the response. Based on it, first in a small paragrpah describe usefulness of the technology. Then list its best features.Use modern language and ensure the description is technical but easy to understand. Highlight key features, advantages, and practical applications in a structured format. Use technical terms.';

//Asking GPT3.5 to take the tutorial generated by GPT4 and create features list of its uses
export const RESPONSE_USER_USE =
  'Based on the following Technical Tutorial guide, provide a short explanation of what this technology is best for, maximum 350 characters. Ensure the content is formatted in HTML using tags such as p, h4, h5, h6, strong, ul, etc. Do not use markdown language do not use h1, h2, h3 tags. Highlight key features and advantages, straight to the point way, in a pragragraph with simple title in <strong> tag and then add one <ul> with 3 <li> of best features. Present the information in technical but easy-to-understand language.';
