name: Trendflow Client CI

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    types: ['closed']
    paths:
      - client/**

env:
  SSH_KEY_PATH: ~/.ssh/id_rsa
  # The path which contains the client code on the server
  DEST_PATH: /var/www/trendflow/client

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
        working-directory: ./client
      - name: npm run build
        run: npm run build
        working-directory: ./client
      - name: Prep SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY_TRENDFLOW }}" > ${{ env.SSH_KEY_PATH }}
          chmod 600 ${{ env.SSH_KEY_PATH }}
      - name: copy files
        run: rsync -r --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${{ env.SSH_KEY_PATH }}" client/dist trendflow@${{ secrets.DO_SERVER_IP }}:${{ env.DEST_PATH }}
