# name: Trendflow Server CI

# env:
#   # The path which contains the application code on the server
#   DEST_PATH: /var/www/trendflow

# on:
#   workflow_dispatch:
#   pull_request:
#     branches: ['main']
#     paths-ignore:
#       - client/**
#       - CONTRIBUTING.md
#       - LICENSE.md
#       - README.md

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: npm install
#         run: npm install
#       - name: Install Babel CLI
#         run: npm install --global @babel/core @babel/cli
#       - name: Build email templates
#         run: babel emails --out-dir dist/emails --extensions ".js,.jsx"
#       - name: Configure SSH
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$SSH_KEY" > ~/.ssh/production.key
#           chmod 600 ~/.ssh/production.key
#           cat >>~/.ssh/config <<END
#           Host production
#             HostName $SSH_HOST
#             User $SSH_USER
#             IdentityFile ~/.ssh/production.key
#             StrictHostKeyChecking no
#           END
#         env:
#           SSH_USER: ${{ secrets.DO_SSH_USER }}
#           SSH_KEY: ${{ secrets.DO_SSH_KEY_TRENDFLOW }}
#           SSH_HOST: ${{ secrets.DO_SERVER_IP }}
#       - name: copy files
#         run: rsync -r --delete --exclude=client/** --exclude=.github/** --exclude=.git/ --exclude=ecosystem.config.cjs --exclude=.env.* --exclude=assets/** . production:${{ env.DEST_PATH }}
#       - name: Restart pm2
#         run: ssh production 'pm2 restart ${{ env.DEST_PATH }}/ecosystem.config.cjs --env production --update-env'
