name: Trendflow Server CI

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths-ignore:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest

#    steps:
#      - uses: actions/checkout@v4
#      - name:
