import mongoose from 'mongoose';
//building the database schema
const TrendSchema = new mongoose.Schema(
  {
    trend: String,
    category: String,
    trendCategory: {
      type: String,
      enum: [
        'Programming Languages',
        'Frontend Development',
        'Backend Development',
        'Frontend Framework',
        'Backend Framework',
        'Data Science',
        'Database Technologies',
        'Cybersecurity',
        'Software as a Service',
        'User Experience',
        'Virtual Reality',
        'Quality Assurance',
        'Testing',
        'Cloud Computing',
        'API Development Tools',
        'Frameworks',
        'Web Technologies',
        'Edge Computing',
        'Natural Language',
        'Machine Learning',
      ],
      default: 'Programming Languages',
    },
    trendTech: {
      type: String,
      enum: [
        'Python',
        'JavaScript',
        'Java',
        'C#',
        'C++',
        'C',
        'Ruby',
        'PHP',
        'Swift',
        'Kotlin',
        'Go',
        'TypeScript',
        'Scala',
        'Rust',
        'R',
        'Objective-C',
        'Perl',
        'Dart',
        'Lua',
        'Groovy',
        'Elixir',
        'F#',
        'Haskell',
        'Clojure',
        'Erlang',
        'Julia',
        'Shell Scripting Languages',
        'MATLAB',
        'Fortran',
        'Ada',
        'Pascal',
        'Prolog',
        'Lisp',
        'Scheme',
        'Assembly Language',
        'VBA',
        'SQL',
        'SAS',
        'AWK',
        'Smalltalk',
        'Delphi/Object Pascal',
        'OCaml',
        'Crystal',
        'Zig',
        'Nim',
        'Ballarina',
        'Elm',
        'ReasonML',
        'HTML',
        'CSS',
        'XML',
        'XHTML',
        'Markdown',
        'YAML',
        'LaTeX',
        'AsciiDoc',
        'SGML',
        'MySQL',
        'PostgreSQL',
        'Microsoft SQL Server',
        'Oracle Database',
        'MongoDB',
        'SQLite',
        'MariaDB',
        'IBM Db2',
        'Redis',
        'Cassandra',
        'Neo4j',
        'Elasticsearch',
        'Couchbase',
        'Firebase Realtime Database',
        'Amazon DynamoDB',
        'CockroachDB',
        'Apache HBase',
        'ArangoDB',
        'Google Cloud Spanner',
        'Aerospike',
        'SAP HANA',
        'InfluxDB',
        'RavenDB',
        'Amazon Aurora',
        'Microsoft Azure SQL Database',
        'Snowflake',
        'Cosmos DB',
        'OrientDB',
        'RethinkDB',
        'ScyllaDB',
        'FaunaDB',
        'FoundationDB',
        'GraphDB',
        'YugaByte DB',
        'TimescaleDB',
        'Amazon Redshift',
        'Teradata',
        'CouchDB',
        'Bigtable',
        'ClickHouse',
        'VoltDB',
        'Greenplum Database',
        'MemSQL',
        'Amazon DocumentDB',
        'TigerGraph',
        'SQLite',
        'PouchDB',
        'RocksDB',
        'Druid',
        'Apache Ignite',
      ],
      default: 'Python',
    },
    trendDesc: {
      type: String,
      default: 'description',
    },
  },
  { timestamps: true }
);
//Name of the table is Trend
export default mongoose.model('Trend', TrendSchema);
